port: 19061

#env: development
#env: product

#db: mongodb://172.16.30.120:27017/room-booking
db: mongodb://127.0.0.1:27018/room-booking
redis: redis://127.0.0.1:6379/0
mqtt: mqtt://127.0.0.1:1883
mqttTopic: devices

# log
logger:
    level: debug
    file: false
    console: true

# jwt
security:
    jwtSecret: QWZZuUjA

uploads: uploads/

# 用户过期时间 (day)
user_expire_time: 30
